"""Standalone local HTML dashboard generated from recorded paper-account data."""

import json
from pathlib import Path


HTML = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Faber Paper Account</title><style>
:root{color-scheme:dark;--bg:#101725;--panel:#182338;--line:#2d3c54;--muted:#aab7cb;--accent:#63dfba;--gold:#f8ca70}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:#f3f6fb;font:15px/1.5 system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:38px 24px}header{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:28px}h1{font-size:32px;letter-spacing:-1px;margin:5px 0}h2{font-size:19px;margin:0 0 18px}.muted{color:var(--muted)}.eyebrow{color:var(--accent);letter-spacing:2px;font-size:11px;font-weight:700}.badge{padding:8px 14px;border:1px solid var(--line);border-radius:30px;color:var(--accent);white-space:nowrap}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.card,section{border:1px solid var(--line);background:var(--panel);border-radius:14px;padding:22px}.card label{color:var(--muted);display:block;font-size:12px}.value{font-size:27px;font-weight:650;letter-spacing:-.6px;margin:10px 0}.detail{font-size:12px;color:var(--muted)}.grid{display:grid;grid-template-columns:1.4fr 1fr;gap:18px;margin-top:18px}section.full{margin-top:18px}.scroll{overflow:auto}table{border-collapse:collapse;width:100%;font-size:13px}th{text-align:left;color:var(--muted);font-weight:500;font-size:11px;text-transform:uppercase;padding:10px 8px}td{padding:13px 8px;border-top:1px solid var(--line)}.positive{color:var(--accent)}.negative{color:#ffa49d}.pending{color:var(--gold)}.chart{width:100%;height:180px;margin-bottom:10px}button{background:none;border:1px solid var(--line);color:var(--muted);padding:7px 13px;border-radius:8px;cursor:pointer}button.active{background:var(--line);color:white}.tabs{display:flex;gap:8px;margin-bottom:16px}.status-list{list-style:none;padding:0;margin:0}.status-list li{padding:11px 0;border-top:1px solid var(--line);font-size:13px}.status-list li:first-child{border:0}.empty{padding:24px 0;color:var(--muted)}footer{margin-top:25px;color:var(--muted);font-size:12px;max-width:1000px}@media(max-width:760px){.cards{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}h1{font-size:26px}.value{font-size:22px}header{align-items:flex-start}}@media(max-width:450px){.cards{grid-template-columns:1fr}header{display:block}.badge{display:inline-block;margin-top:12px}}
</style></head><body><main>
<header><div><div class="eyebrow">MARKET ANOMALY SCANNER · PAPER TRADING</div><h1>Faber paper account</h1><div id="dates" class="muted"></div></div><span id="badge" class="badge"></span></header>
<div class="cards" id="cards"></div>
<div class="grid"><section><h2>Recorded account value</h2><div id="chart"></div><div class="detail">Recorded observations only. This is not a complete daily return or drawdown curve.</div></section><section><h2>Daily runner</h2><ul id="messages" class="status-list"></ul></section></div>
<section class="full"><h2>Holdings</h2><div class="scroll"><table><thead><tr><th>ETF</th><th>Shares</th><th>Cost basis</th><th>Last marked value</th><th>Unrealized P&amp;L</th></tr></thead><tbody id="holdings"></tbody></table></div></section>
<section class="full"><h2>Monthly signals</h2><div id="signal-date" class="detail"></div><div class="scroll"><table><thead><tr><th>ETF</th><th>Target</th><th>Above / below MA</th><th>Confirmed signal</th><th>Developing signal</th></tr></thead><tbody id="signals"></tbody></table></div></section>
<section class="full"><h2>Plans and recorded fills</h2><div class="tabs"><button id="plans-button" class="active">Plans</button><button id="fills-button">Fills</button></div><div id="history" class="scroll"></div></section>
<footer>This local page updates when you run <code>python -m scanner.paper_daily</code>; refresh the browser afterward. All fills are simulated at dated closing prices with recorded fee/slippage assumptions. No broker orders. P&amp;L excludes unrecorded dividends, interest, and corporate actions. The developing monthly signal is informational until month-end confirmation.</footer>
</main><script id="account-data" type="application/json">__DATA__</script><script>
const {ledger,signals,run}=JSON.parse(document.getElementById('account-data').textContent);
const a=ledger.account,last=ledger.valuations.at(-1),current=last&&last.account_revision===a.revision;
const money=c=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(c/100);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cls=n=>n<0?'negative':'positive';
const cashOnly=Object.values(a.positions).every(p=>p.shares===0);
const value=current?last.equity_cents:cashOnly?a.cash_cents:null;
document.getElementById('dates').textContent=`Run ${run.as_of} · Prices ${run.price_date} · Opened ${a.opened_on}`;
document.getElementById('badge').textContent=run.status==='REVIEW'?'Needs review':run.messages.some(m=>m.startsWith('WAITING:'))?'Waiting for a later session':'Paper account updated';
const card=(label,value,detail,c='')=>`<div class="card"><label>${esc(label)}</label><div class="value ${c}">${esc(value)}</div><div class="detail">${esc(detail)}</div></div>`;
document.getElementById('cards').innerHTML=card('Account value',value===null?'Needs a mark':money(value),current?`Marked ${last.date}`:'Recorded cash-only balance')+card('Cash',money(a.cash_cents),'Available paper-account cash')+card('Recorded P&L',value===null?'—':money(value-a.initial_cents),'Since account initialization',value===null?'':cls(value-a.initial_cents))+card('Pending plans',ledger.plans.filter(p=>p.status==='PENDING').length,'Future eligible simulated fills');
document.getElementById('messages').innerHTML=run.messages.map(m=>`<li>${esc(m)}</li>`).join('');
const points=[{date:a.opened_on,equity_cents:a.initial_cents},...ledger.valuations];
if(points.length===1){document.getElementById('chart').innerHTML='<div class="empty">Account opened. Equity history starts when its first session is marked.</div>';}else{const vals=points.map(p=>p.equity_cents),lo=Math.min(...vals),hi=Math.max(...vals),span=Math.max(hi-lo,100);const poly=points.map((p,i)=>`${50+i/(points.length-1)*660},${135-(p.equity_cents-lo)/span*100}`).join(' ');document.getElementById('chart').innerHTML=`<svg class="chart" viewBox="0 0 760 180" role="img" aria-label="Account values at recorded observations"><line x1="50" y1="140" x2="710" y2="140" stroke="#2d3c54"/><polyline points="${poly}" fill="none" stroke="#63dfba" stroke-width="3"/><text x="50" y="20" fill="#aab7cb" font-size="12">${esc(money(hi))}</text><text x="50" y="165" fill="#aab7cb" font-size="12">${esc(points[0].date)}</text><text x="710" y="165" text-anchor="end" fill="#aab7cb" font-size="12">${esc(points.at(-1).date)}</text></svg>`;}
document.getElementById('holdings').innerHTML=Object.entries(a.positions).map(([t,p])=>{const h=current?last.holdings.find(h=>h.ticker===t):null;return `<tr><td><strong>${esc(t)}</strong></td><td>${p.shares}</td><td>${money(p.cost_cents)}</td><td>${h?money(h.value_cents):'—'}</td><td class="${h?cls(h.unrealized_cents):''}">${h?money(h.unrealized_cents):'—'}</td></tr>`;}).join('');
document.getElementById('signal-date').textContent=`Confirmed ${signals.signal_date} · allocation month ${signals.allocation_month} · cash target ${(signals.cash_weight*100).toFixed(0)}%`;
document.getElementById('signals').innerHTML=signals.slots.map(s=>`<tr><td><strong>${esc(s.ticker)}</strong></td><td>${(s.target_weight*100).toFixed(0)}%</td><td class="${cls(s.distance_pct)}">${s.distance_pct>=0?'+':''}${s.distance_pct.toFixed(2)}%</td><td>${s.signal==='ASSET'?'ETF':'Cash'}</td><td>${s.developing_signal===null?'—':s.developing_signal==='ASSET'?'ETF':'Cash'}</td></tr>`).join('');
function showHistory(kind){document.getElementById('plans-button').classList.toggle('active',kind==='plans');document.getElementById('fills-button').classList.toggle('active',kind==='fills');let rows,head;if(kind==='plans'){head='<tr><th>Plan</th><th>Signal date</th><th>Created</th><th>Status</th><th>Orders</th><th>Fee / slippage</th></tr>';rows=ledger.plans.map(p=>`<tr><td>${esc(p.id)}</td><td>${esc(p.signal_date)}</td><td>${esc(p.created_on)}</td><td class="${p.status==='PENDING'?'pending':''}">${esc(p.status)}</td><td>${esc(p.orders.map(o=>`${o.side} ${o.shares} ${o.ticker}`).join('; ')||'No position changes')}</td><td>${money(p.fee_cents)} / ${esc(p.slippage_bps)} bps</td></tr>`);}else{head='<tr><th>Date</th><th>ETF</th><th>Side</th><th>Shares</th><th>Modeled fill</th><th>Fee</th></tr>';rows=ledger.events.filter(e=>e.kind==='FILL').map(e=>`<tr><td>${esc(e.date)}</td><td>${esc(e.ticker)}</td><td>${esc(e.side)}</td><td>${e.shares}</td><td>${money(Number(e.fill_price)*100)}</td><td>${money(e.fee_cents)}</td></tr>`);}document.getElementById('history').innerHTML=rows.length?`<table><thead>${head}</thead><tbody>${rows.join('')}</tbody></table>`:'<div class="empty">No recorded fills yet.</div>';}
document.getElementById('plans-button').addEventListener('click',()=>showHistory('plans'));document.getElementById('fills-button').addEventListener('click',()=>showHistory('fills'));showHistory('plans');
</script></body></html>'''


def write_dashboard(path, ledger, signals, run):
    payload = json.dumps({"ledger": ledger, "signals": signals, "run": run}, ensure_ascii=True)
    # JSON is data, never script; escaping '<' prevents a closing-script injection.
    payload = payload.replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")
    Path(path).write_text(HTML.replace("__DATA__", payload), encoding="utf-8")
